// Données du questionnaire CDAEIA
import { Section, Question } from './cdaeia-types';

export const QUESTIONNAIRE_SECTIONS: Section[] = [
  {
    id: 'profil',
    title: 'Profil de l\'Entreprise',
    description: 'Informations générales sur votre entreprise',
    icon: 'Building',
    questions: [
      {
        id: 'company_name',
        section: 'profil',
        text: 'Quel est le nom légal de votre entreprise?',
        type: 'text',
        required: true,
      },
      {
        id: 'company_neq',
        section: 'profil',
        text: 'Quel est votre NEQ (Numéro d\'entreprise du Québec)?',
        type: 'text',
        required: false,
        helpText: 'Format: 10 chiffres (ex: 1234567890)',
      },
      {
        id: 'email',
        section: 'profil',
        text: 'Quel est votre courriel professionnel?',
        type: 'email',
        required: true,
        helpText: 'Pour recevoir votre rapport et nos recommandations',
      },
      {
        id: 'industry',
        section: 'profil',
        text: 'Dans quel secteur d\'activité principal opérez-vous?',
        type: 'select',
        required: true,
        options: [
          { value: 'saas', label: 'SaaS / Logiciel en tant que service' },
          { value: 'software_dev', label: 'Développement de logiciels' },
          { value: 'it_consulting', label: 'Consultation en TI' },
          { value: 'data_analytics', label: 'Analyse de données / BI' },
          { value: 'cybersecurity', label: 'Cybersécurité' },
          { value: 'fintech', label: 'FinTech' },
          { value: 'healthtech', label: 'HealthTech' },
          { value: 'ai_ml', label: 'Intelligence artificielle / ML' },
          { value: 'cloud_services', label: 'Services cloud / Infrastructure' },
          { value: 'other_tech', label: 'Autre (secteur technologique)' },
        ],
      },
      {
        id: 'total_employees',
        section: 'profil',
        text: 'Combien d\'employés compte votre entreprise au total?',
        type: 'number',
        required: true,
        validation: { min: 1 },
      },
      {
        id: 'is_tax_exempt',
        section: 'profil',
        text: 'Votre entreprise est-elle exonérée d\'impôt?',
        type: 'boolean',
        required: true,
        helpText: 'Les OBNL et organismes exonérés ne sont pas éligibles au CDAEIA.',
      },
      {
        id: 'is_crown_corp',
        section: 'profil',
        text: 'Votre entreprise est-elle une société d\'État?',
        type: 'boolean',
        required: true,
      },
      {
        id: 'is_subsidiary',
        section: 'profil',
        text: 'Votre entreprise est-elle une filiale d\'une société étrangère?',
        type: 'boolean',
        required: true,
        helpText: 'Important: Les filiales étrangères voient leur crédit réduit de 50%.',
      },
    ],
  },
  {
    id: 'revenus',
    title: 'Tests de Revenus',
    description: 'Analyse de la structure de vos revenus (tests 75% et 50%)',
    icon: 'DollarSign',
    questions: [
      {
        id: 'total_revenue',
        section: 'revenus',
        text: 'Quel est votre revenu brut total pour le dernier exercice financier?',
        type: 'currency',
        required: true,
        validation: { min: 0 },
        helpText: 'Revenus bruts avant déductions.',
      },
      {
        id: 'it_revenue',
        section: 'revenus',
        text: 'Combien provient d\'activités du secteur des technologies de l\'information?',
        type: 'currency',
        required: true,
        validation: { min: 0 },
        helpText: 'Développement logiciel, SaaS, consultation TI, intégration systèmes, services cloud, cybersécurité, etc.',
      },
      {
        id: 'software_revenue',
        section: 'revenus',
        text: 'Combien provient spécifiquement de l\'édition de logiciels?',
        type: 'currency',
        required: true,
        validation: { min: 0 },
        helpText: 'Licences logicielles, abonnements SaaS, ventes de produits logiciels.',
      },
      {
        id: 'system_design_revenue',
        section: 'revenus',
        text: 'Combien provient de la conception de systèmes informatiques?',
        type: 'currency',
        required: true,
        validation: { min: 0 },
        helpText: 'Développement sur mesure, intégration, architecture de systèmes.',
      },
      {
        id: 'data_hosting_revenue',
        section: 'revenus',
        text: 'Combien provient du traitement et de l\'hébergement de données?',
        type: 'currency',
        required: true,
        validation: { min: 0 },
        helpText: 'Services cloud, data centers, traitement de données, hébergement.',
      },
    ],
  },
  {
    id: 'effectifs',
    title: 'Effectifs',
    description: 'Détail de vos employés techniques',
    icon: 'Users',
    questions: [
      {
        id: 'tech_employees_count',
        section: 'effectifs',
        text: 'Combien d\'employés travaillent dans des rôles techniques/TI?',
        type: 'number',
        required: true,
        validation: { min: 0 },
        helpText: 'Développeurs, analystes, data scientists, ingénieurs, etc.',
      },
      {
        id: 'tech_employees_fulltime',
        section: 'effectifs',
        text: 'Parmi ceux-ci, combien sont à temps plein (26h+/semaine, 40+ semaines/an)?',
        type: 'number',
        required: true,
        validation: { min: 0 },
        helpText: 'Seuls les employés à temps plein peuvent être éligibles.',
      },
      {
        id: 'total_tech_payroll',
        section: 'effectifs',
        text: 'Quelle est la masse salariale annuelle totale de vos employés techniques?',
        type: 'currency',
        required: true,
        validation: { min: 0 },
        helpText: 'Salaires bruts annuels.',
      },
      {
        id: 'has_ai_specialists',
        section: 'effectifs',
        text: 'Avez-vous des employés spécialisés en IA/ML/Data Science?',
        type: 'boolean',
        required: true,
      },
      {
        id: 'ai_specialists_count',
        section: 'effectifs',
        text: 'Combien de spécialistes IA/ML/Data Science avez-vous?',
        type: 'number',
        required: false,
        validation: { min: 0 },
        conditional: { field: 'has_ai_specialists', value: true },
      },
    ],
  },
  {
    id: 'temps',
    title: 'Allocation du Temps',
    description: 'Répartition du temps de travail par type d\'activité',
    icon: 'Clock',
    questions: [
      {
        id: 'time_tracking_system',
        section: 'temps',
        text: 'Avez-vous un système de suivi du temps pour vos employés techniques?',
        type: 'select',
        required: true,
        options: [
          { value: 'detailed', label: 'Oui, détaillé par type d\'activité', description: 'Ex: Toggl, Harvest' },
          { value: 'basic', label: 'Oui, mais basique', description: 'Heures seulement' },
          { value: 'none', label: 'Non, pas de suivi formel' },
        ],
        helpText: 'Important: Le CDAEIA exige de pouvoir prouver l\'allocation du temps.',
      },
      {
        id: 'avg_time_ai_dev',
        section: 'temps',
        text: 'Quel % du temps est consacré au développement IA?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
        helpText: 'Création de modèles ML, entraînement, fine-tuning, algorithmes IA.',
      },
      {
        id: 'avg_time_ai_integration',
        section: 'temps',
        text: 'Quel % du temps est consacré à l\'intégration de composantes IA?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
        helpText: 'Intégration d\'API ML, déploiement de modèles, MLOps.',
      },
      {
        id: 'avg_time_ai_data',
        section: 'temps',
        text: 'Quel % du temps est consacré à la préparation de données pour l\'IA?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
        helpText: 'ETL pour ML, feature engineering, pipelines de données.',
      },
      {
        id: 'avg_time_ai_analytics',
        section: 'temps',
        text: 'Quel % du temps est consacré à l\'analytique avancée/prédictive?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
        helpText: 'Modèles prédictifs, forecasting, analyse statistique.',
      },
      {
        id: 'avg_time_maintenance',
        section: 'temps',
        text: 'Quel % du temps est consacré à la maintenance de systèmes?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
        helpText: '⚠️ NON ÉLIGIBLE: Corrections de bugs, patches, mises à jour.',
      },
      {
        id: 'avg_time_support',
        section: 'temps',
        text: 'Quel % du temps est consacré au support technique?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
        helpText: '⚠️ NON ÉLIGIBLE: Helpdesk, troubleshooting.',
      },
      {
        id: 'avg_time_admin',
        section: 'temps',
        text: 'Quel % du temps est consacré à l\'administration/réunions?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
        helpText: '⚠️ NON ÉLIGIBLE: Réunions, emails, documentation.',
      },
    ],
  },
  {
    id: 'ia',
    title: 'Intégration IA',
    description: 'Évaluation de vos composantes d\'intelligence artificielle',
    icon: 'Cpu',
    questions: [
      {
        id: 'has_ai_products',
        section: 'ia',
        text: 'Avez-vous des produits ou services qui intègrent de l\'intelligence artificielle?',
        type: 'boolean',
        required: true,
      },
      {
        id: 'ai_technologies',
        section: 'ia',
        text: 'Quelles technologies IA utilisez-vous?',
        type: 'multi_select',
        required: false,
        conditional: { field: 'has_ai_products', value: true },
        options: [
          { value: 'ml_classical', label: 'Machine Learning classique', description: 'Régression, classification, clustering' },
          { value: 'deep_learning', label: 'Deep Learning / Réseaux neuronaux', description: 'CNN, RNN, Transformers' },
          { value: 'nlp', label: 'NLP (Traitement du langage)', description: 'Analyse de texte, chatbots' },
          { value: 'computer_vision', label: 'Computer Vision', description: 'Reconnaissance d\'images, OCR' },
          { value: 'predictive_analytics', label: 'Analytique prédictive', description: 'Forecasting, scoring' },
          { value: 'llm', label: 'LLM / IA générative', description: 'GPT, Claude, génération de contenu' },
          { value: 'recommendation', label: 'Systèmes de recommandation', description: 'Personnalisation' },
          { value: 'automation', label: 'Automatisation intelligente', description: 'RPA avec IA' },
        ],
      },
      {
        id: 'ai_maturity',
        section: 'ia',
        text: 'Comment décririez-vous la maturité de vos initiatives IA?',
        type: 'select',
        required: true,
        conditional: { field: 'has_ai_products', value: true },
        options: [
          { value: 'experimental', label: 'Expérimental', description: 'POC, tests, exploration' },
          { value: 'pilot', label: 'Pilote', description: 'Projets limités en production' },
          { value: 'scaling', label: 'En expansion', description: 'Plusieurs projets IA en production' },
          { value: 'mature', label: 'Mature', description: 'IA intégrée dans les opérations' },
          { value: 'ai_first', label: 'IA-native', description: 'L\'IA est au coeur de notre offre' },
        ],
      },
      {
        id: 'ai_revenue_percentage',
        section: 'ia',
        text: 'Quel pourcentage de vos revenus provient de produits/services intégrant l\'IA?',
        type: 'percentage',
        required: true,
        validation: { min: 0, max: 100 },
      },
    ],
  },
  {
    id: 'documentation',
    title: 'Documentation',
    description: 'État de votre documentation et préparation aux audits',
    icon: 'FileText',
    questions: [
      {
        id: 'has_technical_docs',
        section: 'documentation',
        text: 'Avez-vous une documentation technique de vos projets IA?',
        type: 'select',
        required: true,
        options: [
          { value: 'comprehensive', label: 'Complète', description: 'Architecture, modèles, datasets, métriques' },
          { value: 'partial', label: 'Partielle', description: 'Quelques documents' },
          { value: 'minimal', label: 'Minimale', description: 'Peu ou pas de documentation' },
        ],
      },
      {
        id: 'has_time_records',
        section: 'documentation',
        text: 'Conservez-vous des historiques de feuilles de temps?',
        type: 'select',
        required: true,
        options: [
          { value: '6_years_plus', label: '6 ans ou plus' },
          { value: '3_5_years', label: '3-5 ans' },
          { value: '1_2_years', label: '1-2 ans' },
          { value: 'none', label: 'Non' },
        ],
        helpText: 'Les données doivent être conservées au moins 6 ans.',
      },
      {
        id: 'previous_cdae',
        section: 'documentation',
        text: 'Avez-vous déjà réclamé le crédit CDAE par le passé?',
        type: 'boolean',
        required: true,
      },
      {
        id: 'audit_readiness',
        section: 'documentation',
        text: 'Comment évaluez-vous votre préparation à un audit?',
        type: 'select',
        required: true,
        options: [
          { value: '1', label: '1 - Pas prêt' },
          { value: '2', label: '2 - Peu prêt' },
          { value: '3', label: '3 - Moyennement prêt' },
          { value: '4', label: '4 - Bien prêt' },
          { value: '5', label: '5 - Très prêt' },
        ],
      },
    ],
  },
];

export function getQuestionById(id: string): Question | undefined {
  for (const section of QUESTIONNAIRE_SECTIONS) {
    const question = section.questions.find(q => q.id === id);
    if (question) return question;
  }
  return undefined;
}

export function getSectionById(id: string): Section | undefined {
  return QUESTIONNAIRE_SECTIONS.find(s => s.id === id);
}
